### ISSUE TITLE
URL Parameters not encoded | 400 bad request

### ISSUE THREAD

**Issue by FireMasterK** [ipfs-shipyard/java-ipfs-http-client#181]
```
java.lang.RuntimeException: IOException contacting IPFS daemon.
400 Bad Request
Trailer: null
	at io.ipfs.api.IPFS.get(IPFS.java:731)
	at io.ipfs.api.IPFS.retrieve(IPFS.java:687)
	at io.ipfs.api.IPFS.retrieveAndParse(IPFS.java:649)
	at io.ipfs.api.IPFS.access$100(IPFS.java:15)
	at io.ipfs.api.IPFS$Pubsub.pub(IPFS.java:280)
	at me.kavin.piped.ipfs.IPFS.lambda$0(IPFS.java:15)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://127.0.0.1:5001/api/v0/pubsub/pub?arg=UCTkXRDQl0luXxVQrRQvWS6w&arg={"id":"UCTkXRDQl0luXxVQrRQvWS6w","name":"Dream","avatarUrl":"https://pipedproxy.kavin.rocks/ytc/AAUvwnj0D0T3HRCp3f2D2pHkyhBkIt8MZG2HB9_mUkgMyg=s48-c-k-c0x00ffffff-no-rw?host=yt3.ggpht.com","bannerUrl":"https://pipedproxy.kavin.rocks/eTIvFjkXp15Y__EfbVA5UNDxp2rrAqkxht7E4yolNVNyvJFvHXphhyUgyboyU4YjaZxG0lKA1g=w1060-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rw?host=yt3.ggpht.com","description":"Minecraft stuff, yes, my IGN is Dream","nextpage":"https://www.youtube.com/browse_ajax?ctoken=4qmFsgKBARIYVUNUa1hSRFFsMGx1WHhWUXJSUXZXUzZ3GjZFZ1oyYVdSbGIzTVlBeUFBTUFFNEFlb0RFME5uUVZORFoycGlPRTVQVEhKWmNuWnVialElM0SaAixicm93c2UtZmVlZFVDVGtYUkRRbDBsdVh4VlFyUlF2V1M2d3ZpZGVvczEwMg%3D%3D&continuation=4qmFsgKBARIYVUNUa1hSRFFsMGx1WHhWUXJSUXZXUzZ3GjZFZ1oyYVdSbGIzTVlBeUFBTUFFNEFlb0RFME5uUVZORFoycGlPRTVQVEhKWmNuWnVialElM0SaAixicm93c2UtZmVlZFVDVGtYUkRRbDBsdVh4VlFyUlF2V1M2d3ZpZGVvczEwMg%3D%3D&itct=CCUQ6IsCGAAiEwjSk4itw_PuAhXLK-AKHdvCDyw=","relatedStreams":[{"url":"/watch?v=a8ds6SnOGow","title":"Minecraft Speedrunner VS 4 Hunters GRAND FINALE","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/a8ds6SnOGow/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"1 week ago","duration":2362,"views":24743170},{"url":"/watch?v=k4v6slOxxXs","title":"Minecraft Speedrunner VS 4 Hunters FINALE REMATCH","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/k4v6slOxxXs/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"1 month ago","duration":2988,"views":31509347},{"url":"/watch?v=hDkuUZ3F1GU","title":"Minecraft Speedrunner VS 4 Hunters FINALE","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/hDkuUZ3F1GU/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"2 months ago","duration":2953,"views":37716475},{"url":"/watch?v=R7klyFU_6xM","title":"Minecraft Survivalist VS 3 Hitmen","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/R7klyFU_6xM/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"2 months ago","duration":2404,"views":30450511},{"url":"/watch?v=Sxgj9unnN6E","title":"Minecraft, But It's Pitch Black...","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/Sxgj9unnN6E/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"3 months ago","duration":2026,"views":12068181},{"url":"/watch?v=CrtuA5HWFoU","title":"Minecraft Speedrunner VS 4 Hunters REMATCH","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/CrtuA5HWFoU/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"3 months ago","duration":2709,"views":47002496},{"url":"/watch?v=mltj5p6l1-8","title":"Minecraft, But We Can Only See One Chunk...","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/mltj5p6l1-8/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"5 months ago","duration":1549,"views":18769314},{"url":"/watch?v=7BCojznmtRE","title":"Minecraft Speedrunner VS 4 Hunters","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/7BCojznmtRE/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"5 months ago","duration":2882,"views":58524356},{"url":"/watch?v=tylNqtyj0gs","title":"Minecraft Speedrunner VS 3 Hunters GRAND FINALE","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/tylNqtyj0gs/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"6 months ago","duration":2508,"views":71090794},{"url":"/watch?v=UHAvoyIptN0","title":"Unsolved Mystery of Herobrine","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/UHAvoyIptN0/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"6 months ago","duration":1013,"views":13967600},{"url":"/watch?v=Y7t5B69G0Dw","title":"Minecraft Speedrunner VS 3 Hunters FINALE REMATCH","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/Y7t5B69G0Dw/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"6 months ago","duration":2820,"views":43569059},{"url":"/watch?v=V_7ZPYXg5-M","title":"Beating Minecraft Without Leaving The Nether...","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/V_7ZPYXg5-M/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"7 months ago","duration":1696,"views":21698654},{"url":"/watch?v=Ds7dX5BtCUA","title":"Minecraft, But The Ender Dragon Is Our Pet...","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/Ds7dX5BtCUA/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"7 months ago","duration":1422,"views":10406575},{"url":"/watch?v=bOOfg7d1b6c","title":"Minecraft Speedrunner VS PRO","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/bOOfg7d1b6c/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"7 months ago","duration":3858,"views":25435506},{"url":"/watch?v=hgdSJdeGF_0","title":"Minecraft Speedrunner VS 3 Hunters FINALE","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/hgdSJdeGF_0/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"7 months ago","duration":2763,"views":48025735},{"url":"/watch?v=sJW4Le1CX-g","title":"Dream VS Technoblade (Minecraft Championship)","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/sJW4Le1CX-g/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"8 months ago","duration":2206,"views":11188401},{"url":"/watch?v=-As3w9Hhl88","title":"Minecraft Speedrun World Record 1.15","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/-As3w9Hhl88/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"8 months ago","duration":1363,"views":21342890},{"url":"/watch?v=RTXS4MMngnA","title":"Minecraft Speedrunner VS 3 Hunters REMATCH","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/RTXS4MMngnA/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"8 months ago","duration":2825,"views":44937175},{"url":"/watch?v=baNF5qF_gdo","title":"3 Minecraft Speedrunners VS Hunter ft. MrBeast","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/baNF5qF_gdo/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"8 months ago","duration":1169,"views":26504923},{"url":"/watch?v=VSNMNM8Qouw","title":"Minecraft, But It's a Zombie Apocalypse","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/VSNMNM8Qouw/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"8 months ago","duration":1739,"views":23607768},{"url":"/watch?v=3tH4dyOPZnY","title":"Minecraft Speedrunner VS 3 Hunters","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/3tH4dyOPZnY/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"9 months ago","duration":2182,"views":42692647},{"url":"/watch?v=MsDhoUEa6JE","title":"Minecraft, But Three People Control One Player...","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/MsDhoUEa6JE/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"9 months ago","duration":1805,"views":21038862},{"url":"/watch?v=EIK_88hdJl4","title":"Minecraft Speedrunner VS Hunter LIVE","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/EIK_88hdJl4/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"9 months ago","duration":1138,"views":4959886},{"url":"/watch?v=zEmLyLBEQHc","title":"Minecraft Ultimate Tag...","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/zEmLyLBEQHc/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"9 months ago","duration":1390,"views":11599664},{"url":"/watch?v=kygSV5CJkO8","title":"Minecraft Speedrunner VS 2 Hunters","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/kygSV5CJkO8/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"9 months ago","duration":1936,"views":33029154},{"url":"/watch?v=p34C7fNFgTA","title":"Minecraft Block Shuffle...","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/p34C7fNFgTA/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"10 months ago","duration":1522,"views":32244366},{"url":"/watch?v=KjRfXURKAx8","title":"Minecraft Death Swap 2...","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/KjRfXURKAx8/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"10 months ago","duration":1206,"views":22659058},{"url":"/watch?v=O60zJzhYGEA","title":"2 Minecraft Speedrunners VS Terminator","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/O60zJzhYGEA/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"10 months ago","duration":1539,"views":23268256},{"url":"/watch?v=JVih1OeNMPs","title":"What If A Player Controlled The Ender Dragon...","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/JVih1OeNMPs/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"10 months ago","duration":1338,"views":6805875},{"url":"/watch?v=fj28UtF0-Fs","title":"Minecraft, But It's The World Record...","thumbnail":"https://pipedproxy.kavin.rocks/vi_webp/fj28UtF0-Fs/mqdefault.webp?host=i.ytimg.com","uploaderName":"Dream","uploaderUrl":"/channel/UCTkXRDQl0luXxVQrRQvWS6w","uploadedDate":"10 months ago","duration":1651,"views":11915772}]}
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1932)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
	at io.ipfs.api.IPFS.get(IPFS.java:718)
	... 10 more
```

**Comment by FireMasterK** [comment]
Temporary fix: encode it myself.

**Comment by kevodwyer** [comment]
pubsub api was updated in commit: https://github.com/ipfs-shipyard/java-ipfs-http-client/commit/f8a49af39f92d3a9af6c6cbfee10f797bc3efc57

closing issue as resolved
