### ISSUE TITLE
PubSub url are not properly encoded

### ISSUE THREAD

**Issue by romainreuillon** [ipfs-shipyard/java-ipfs-http-client#87]
Dear dev,

when trying to publish an message with spaces and special characters I got this:
```
[error] Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://104.45.15.171:5001/api/v0/pubsub/pub?arg=toto&arg=Life is great!
[error] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913)
[error] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:97)
[error] 	at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1501)
[error] 	at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1499)
[error] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:793)
[error] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[error] 	at io.ipfs.api.IPFS.get(IPFS.java:580)
[error] 	at io.ipfs.api.IPFS.retrieve(IPFS.java:571)
[error] 	at io.ipfs.api.IPFS.retrieveAndParse(IPFS.java:553)
[error] 	at io.ipfs.api.IPFS.access$100(IPFS.java:15)
[error] 	at io.ipfs.api.IPFS$Pubsub.pub(IPFS.java:235)
```

URL doesn't seems to be encoded.

Romain

**Comment by kevodwyer** [comment]
I believe this is resolved as i don't see two arg params to pubsub/pub api call now. Closing as stale, feel free to re-open with more detail if required
